# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 961bfae9de00fda9a2e966bf5cb4f3b21e7aa6b38464f33977ad62c075094778adb41f6d9d44e983deb9c33ccc9991e214eb454a947cad7728550ed5bd65c914

test:
  secret_key_base: bb69c8b8e55acb2c8a7401f3060d051e423f97f142317cc3ab623c0afbb38a119d95db8465be6bfdbe7038d0f90503fba15f43bb10ed606454295b588c85f0b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
